name: Unit test
on: [ push, pull_request ]

jobs:
  build:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.3
      - name: Composer install
        run: composer install
      - name: Run PHPUnit
        run: vendor/bin/phpunit tests/
